name: EnthusiaKOTH
main: com.enthusia.koth.EnthusiaKothPlugin
version: ${version}
api-version: '1.21'
authors: [Enthusia]
description: Modular KOTH framework for Enthusia.
softdepend: [Vault, PlaceholderAPI, LumaGuilds]
commands:
  ekoth:
    description: EnthusiaKOTH command.
    usage: /ekoth
    permission: enthusiakoth.command
permissions:
  enthusiakoth.command:
    default: false
  enthusiakoth.start.basic:
    default: false
  enthusiakoth.start.advanced:
    default: false
  enthusiakoth.admin:
    default: op
    children:
      enthusiakoth.command: true
      enthusiakoth.test.start: true
      enthusiakoth.test.join: true
  enthusiakoth.test.start:
    default: op
    children:
      enthusiakoth.command: true
  enthusiakoth.test.join:
    default: false
    children:
      enthusiakoth.command: true
